### ISSUE TITLE
Settings button is redundant

### ISSUE THREAD

**Issue by chimosky** [marsian83/GoatCabbageWolfActivity#2]
Settings button seems to be redundant, and only prints `Coming Soon` in the logs which isn't helpful, please remove it.

**Comment by marsian83** [comment]
I have commented out this, till the time the functionality of it is not developed

**Comment by chimosky** [comment]
When would you be building the settings functionality?

**Comment by marsian83** [comment]
> When would you be building the settings functionality?

I will do it later this week, in the event I was talking about right now

**Comment by chimosky** [comment]
I'll leave this open till you do.

**Comment by marsian83** [comment]
Hi @chimosky , I have returned from the event
I have also added a simple change theme option in the settings screen, can you check

**Comment by marsian83** [comment]
![image](https://github.com/user-attachments/assets/e88f595c-eb69-4f6f-b145-40eee5a05708)

**Comment by chimosky** [comment]
Tested 31cae37, works as expected.

The libpng errors are still seen in the logs.

It'll be nice to have the farmer facing the direction he's headed in, he's currently only facing one direction.

It'll also be nice to control the direction the boat moves in using arrow keys, I'll open another issue for that later.
