### ISSUE TITLE
Flake8 issues

### ISSUE THREAD

**Issue by chimosky** [marsian83/GoatCabbageWolfActivity#3]
flake8 currently shows about 33 errors, check them out and fix them.

**Comment by marsian83** [comment]
Fixed flake8 specific to the code I wrote, There were some flake8 errors in the sugargame file which I copied from another repo, Do you reckon I should make changes to it?

**Comment by chimosky** [comment]
> Fixed flake8 specific to the code I wrote, There were some flake8 errors in the sugargame file which I copied from another repo, Do you reckon I should make changes to it?

Try to update your sugargame repo and see if those errors have been fixed.

**Comment by marsian83** [comment]
> > Fixed flake8 specific to the code I wrote, There were some flake8 errors in the sugargame file which I copied from another repo, Do you reckon I should make changes to it?
> 
> Try to update your sugargame repo and see if those errors have been fixed.

Yes, updating those files, fixes them
